### ISSUE TITLE
安装opencv库后依旧无法导入cv2

### ISSUE THREAD

**Issue by Kelcoin** [GWYOG/GWYOG-Hoshino-plugins#19]
`[2020-12-03 19:02:36,075 nonebot] ERROR: Failed to import "hoshino.modules.pcrsealkiller.sealkiller", error: DLL load failed while importing cv2: 找不到指定的模块。
[2020-12-03 19:02:36,075 nonebot] ERROR: DLL load failed while importing cv2: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrsealkiller\sealkiller.py", line 32, in <module>
    opencv_util = importlib.import_module(RELATIVE_PATH.replace(os.sep,'.') + '._opencv_util')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrsealkiller\_opencv_util.py", line 1, in <module>
    import cv2
ImportError: DLL load failed while importing cv2: 找不到指定的模块。
`

Windows Server 2008 
Python 3.8
opencv-python     3.4.11.45

**Comment by Kelcoin** [comment]
![image](https://user-images.githubusercontent.com/10922375/101001931-b56d3180-359a-11eb-8737-be02afbf525b.png)
根据网上方法使用depends打开CV2.CP38-WIN_AMD64.PYD后发现似乎缺失大量dll

**Comment by GWYOG** [comment]
emmm...我也不清楚这是为什么，只能帮你百度一下。
[这个博客](http://blog.sina.com.cn/s/blog_cfcad9b00102y25x.html)提到的一些解决办法看起来还算靠谱，比如检查下自己Visual C++ 2015等环境有没有安装。

**Comment by sanshanya** [comment]
试试在服务器添加功能里勾选‘用户与基础体验’里的桌面体验

**Comment by Kelcoin** [comment]
> 试试在服务器添加功能里勾选‘用户与基础体验’里的桌面体验

感谢，解决了
