### ISSUE TITLE
卡片集换插件的报错

### ISSUE THREAD

**Issue by Watanabe-Asa** [GWYOG/GWYOG-Hoshino-plugins#21]
[2020-12-04 01:31:53,195 卡片集换] ERROR: <class 'IndexError'> occured when auto_mix_card handling message -978403562.
[2020-12-04 01:31:53,195 卡片集换] ERROR: tuple index out of range
Traceback (most recent call last):
  File "/root/bot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/bot/HoshinoBot/hoshino/modules/pokemanpcr/poke_man_pcr.py", line 460, in auto_mix_card
    card_counter, card_descs, card = get_random_cards(db.get_cards_num(ev.group_id, ev.user_id), row_num, col_num, mix_rounds, False, get_random_cards_list, super_rare_prob, rare_prob)
  File "/root/bot/HoshinoBot/hoshino/modules/pokemanpcr/poke_man_pcr.py", line 210, in get_random_cards
    base.paste(img, (coor_x, coor_y), mask=img.split()[3])
IndexError: tuple index out of range

某群友一键一键合成时出现数组越界的情况，导致没有回复卡片也没了。这里的越界出现在amount判断之前。

**Comment by Watanabe-Asa** [comment]
[2020-12-04 00:54:31,345 nonebot] ERROR: An exception occurred while handling event notice.notify.poke:
[2020-12-04 00:54:31,345 nonebot] ERROR: tuple index out of range
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/notice_request.py", line 83, in handle_notice_or_request
    await _bus.emit(ev_name, session)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/bus.py", line 57, in emit
    results += await run_async_funcs(self._subscribers[event],
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/utils.py", line 41, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "/root/bot/HoshinoBot/hoshino/service.py", line 367, in wrapper
    return await func(session)
  File "/root/bot/HoshinoBot/hoshino/modules/pokemanpcr/poke_man_pcr.py", line 338, in poke_back
    card_counter, card_descs, card = get_random_cards(db.get_cards_num(session.ctx['group_id'], session.ctx['user_id']), card_file_names_all,
  File "/root/bot/HoshinoBot/hoshino/modules/pokemanpcr/poke_man_pcr.py", line 208, in get_random_cards
    base.paste(img, (coor_x, coor_y), mask=img.split()[3])
IndexError: tuple index out of range

戳卡也有出现类似问题。

**Comment by GWYOG** [comment]
啊，应该是头像图片的模式不是RGBA导致的...上周Hoshino群有人反馈我以为是个例就没去修，我的我的，晚上回去修

**Comment by GWYOG** [comment]
应该修复了，如果bug还存在就Reopen这个issue

**Comment by Watanabe-Asa** [comment]
非常感谢！
