### ISSUE TITLE
记忆小游戏报错

### ISSUE THREAD

**Issue by ciel2233** [GWYOG/GWYOG-Hoshino-plugins#5]
神经衰弱和完美配对，机器人撤回消息后都会报错，代码也不继续运行了。
[2020-09-10 16:41:16,759 pcr-neurasthenia] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when neurasthenia_game handling message 2970.
[2020-09-10 16:41:16,759 pcr-neurasthenia] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xcwbot\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\xcwbot\HoshinoBot\hoshino\service.py", line 217, in wrapper
    return await func(bot, event)
  File "C:\Users\Administrator\Desktop\xcwbot\HoshinoBot\hoshino\modules\pcrmemorygames\pcr_neurasthenia.py", line 53, in neurasthenia_game
    await bot.delete_msg(message_id = msg['message_id'])
  File "C:\Program Files\Python38\lib\site-packages\aiocqhttp\__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Program Files\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Program Files\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "C:\Program Files\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>

**Comment by GWYOG** [comment]
你用的是cqhttp-mirai还是go-cqhttp？版本号是多少？
这个应该不是插件代码的问题，怀疑机器人可能被腾讯风控。
如果是go-cqhttp的话后台会显示是否可能被风控。

**Comment by ciel2233** [comment]
我开始用的cqhttp-miraii，现在换成go-cqhttp好了

**Comment by GWYOG** [comment]
OK. 这个仓库的前几个插件我是在cqhttp-mirai环境下开发的，后来改用go-cqhttp了。新的几个插件是否兼容cqhttp-mirai其实我也不太清楚...不过它们在go-cqhttp环境下运行的效果还不错。
